import type { NextPage } from 'next'
import Head from 'next/head'
import { Main } from 'src/components/shared/Main';

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>доедешь-пиши</title>
        {/*FIXME заполнить мета теги*/}
        <meta property="og:site_name" content="доедешь-пиши.рф"/>
        <meta property="og:title" content="Page Title"/>
        <meta property="og:description" content="Page description"/>
        <meta property="og:image" content="https://example.com/image.jpg"/>
        <meta property="og:url" content="https://example.com"/>
        <meta property="og:type" content="website"/>
        {/*<meta name="description" content="Generated by create next app" />*/}
        {/*<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>*/}
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <Main />
      </main>

      <footer>

      </footer>
    </div>
  )
}

export default Home
