import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 style={{color: 'violet'}}>Next js 12.3.4</h1>
        {[...Array(100).keys()].map((_, index) => (
          <div key={index} style={{ height: '100px', color: 'red' }}>
            <h1>Content = {index}</h1>
          </div>
        ))}
      </main>

      <footer>
        {/*<a*/}
        {/*  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"*/}
        {/*  target="_blank"*/}
        {/*  rel="noopener noreferrer"*/}
        {/*>*/}
        {/*  Powered by{' '}*/}
        {/*  <span >*/}
        {/*    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />*/}
        {/*  </span>*/}
        {/*</a>*/}
      </footer>
    </div>
  )
}

export default Home
